/* #undef KARAZEH_RENDERER_OGRE */
/* #undef KARAZEH_RENDERER_QT */
#define KARAZEH_RENDERER_COCOA
/* #undef KARAZEH_RENDERER_GTK3 */
/* #undef KARAZEH_THREADS_QT */
/* #undef KARAZEH_THREADS_BOOST */
/* #undef KARAZEH_THREADS_TBB */
/* #undef KARAZEH_THREADS_POCO */
/* #undef KARAZEH_THREADS_GLIB */
#define KARAZEH_USE_LOG4CPP
#define KARAZEH_REAL_PROGRESS
/* #undef KARAZEH_PERSISTENT */
#define KARAZEH_DEFAULT_RENDERER "Vanilla"
